FROM mcr.microsoft.com/azure-functions/python:4-python3.9

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

RUN cat /etc/apt/sources.list | grep -v jessie > /etc/apt/sources.list.new
RUN mv /etc/apt/sources.list.new /etc/apt/sources.list

# Install essential packages
RUN apt update \
    && apt install -y \
        build-essential \
        cmake \
        git \
        wget \
        unzip

# Install requirements
RUN pip install --upgrade pip
COPY requirements.txt /
RUN pip install -r /requirements.txt

# Copy python code to image
COPY core /home/site/wwwroot/core
COPY setup.py /home/site/wwwroot/setup.py
COPY requirements.txt /home/site/wwwroot/requirements.txt
RUN cd /home/site/wwwroot; pip install .; cd -;
COPY models/host.json /home/site/wwwroot/host.json

# source code for GES and Arima models
COPY models/ges/. /home/site/wwwroot
COPY models/arima_python/. /home/site/wwwroot
