FROM turingcropapp/webappbase:latest

# Upgrading python and installing python libraries
RUN apt update
RUN apt install -y python3.8 python3.8-dev libpython3.8 python3.8-venv
RUN rm /usr/bin/python3 && ln -s /usr/bin/python3.8 /usr/bin/python3
RUN ls -l /usr/bin | grep python
RUN python3 -m pip install --upgrade pip

# install nodejs/npm (requires first installing CURL
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

RUN mkdir CROP
WORKDIR CROP

# Adding crop core
ADD core core

# Adding crop webapp
ADD webapp webapp

# Adding secrets
ADD .secrets .secrets

# Use setup.py to install cropcore
ADD setup.py setup.py
ADD requirements.txt requirements.txt
RUN python3 -m pip install .

# launch the webapp
WORKDIR /CROP/webapp

# Install the Javascript dependencies
RUN npm install

EXPOSE 5000

CMD ["./run.sh"]
