download:
	# This should download model code from repo
container:
	# This should containerise model code
prediction:
	# This should run analysis code
help: 
	$(info download : Download model code from repo)
	$(info container : Containerise model code)
	$(info prediction : Run model code)