# Derived from https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-container-functionapp-on-azure.yml

# Action Requires
# 1. Setup the AZURE_CREDENTIALS secrets in your GitHub Repository
# 2. Setup the REGISTRY_USERNAME secrets in your GitHub Repository
# 3. Setup the REGISTRY_PASSWORD secrets in your GitHub Repository
# 4. Replace REGISTRY, NAMESPACE, IMAGE, TAG in the following template with proper values
# 5. Add this yaml file to your project's .github/workflows/
# 6. Push your local project to your GitHub Repository

name: CropFuncs_Container_Workflow

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master


# do we really need to login and out of azure cli??

 #   - name: 'Login via Azure CLI'
 #     uses: azure/login@v1
 #     with:
 #       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: 'Build main'
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: __app__
      run: |
        docker build -f Dockerfile -t turingcropapp/functions:prod . ;
        docker push turingcropapp/functions:prod ;
    - name: 'Build dev'
      if: ${{ github.ref == 'refs/heads/develop' }}
      working-directory: __app__
      run: |
        docker build -f Dockerfile -t turingcropapp/functions:dev . ;
        docker push turingcropapp/functions:dev ;


    - name: 'Run Azure Functions Container Action main'
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: Azure/functions-container-action@v1
      id: famain
      with:
        app-name: cropappfunctionapp
        image: docker.io/turingcropapp/functions:prod ;
	publish-profile: ${{ secrets.CROPAPPFUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Run Azure Functions Container Action develop'
      if: ${{ github.ref == 'refs/heads/develop' }}
      uses: Azure/functions-container-action@v1
      id: fadev
      with:
        app-name: cropapptestfunctionapp
        image: dockerhub/turingcropapp/functions:dev;
	publish-profile: ${{ secrets.CROPAPPTESTFUNCTIONAPP_PUBLISH_PROFILE }}

# do we really need to login and out of azure cli??

#    - name: Azure logout
#      run: |
#        az logout
# For more information on GitHub Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions