name: "Build and push functions to DockerHub"

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: 'Build main'
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: __app__
        run: |
          docker build -f Dockerfile -t turingcropapp/functions:prod . ;
          docker push turingcropapp/functions:prod ;
      - name: 'Build dev'
        if: ${{ github.ref == 'refs/heads/develop' }}
        working-directory: __app__
        run: |
          docker build -f Dockerfile -t turingcropapp/functions:dev . ;
          docker push turingcropapp/functions:dev ;


