name: "Build and push functions to DockerHub"

on:
  push:
    branches: [main, develop, test-actions]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: 'Build main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker build -f Dockerfile_ingress_functions -t turingcropapp/functions:prod . ;
          docker push turingcropapp/functions:prod ;
      - name: 'Build dev'
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker build -f Dockerfile_ingress_functions -t turingcropapp/functions:dev . ;
          docker push turingcropapp/functions:dev ;
      - name: 'Build test-actions'
        if: ${{ github.ref == 'refs/heads/test-actions' }}
        run: |
          docker build -f Dockerfile_ingress_functions -t turingcropapp/functions:test-actions . ;
          docker push turingcropapp/functions:test-actions ;
